---
ID: "3c815af4-76dc-45ba-a39b-c863d87374ae"
Parent: "ff19b981-d71e-4b4a-ad51-580160a69023"
Template: "ff19b981-d71e-4b4a-ad51-580160a69023"
Path: "/sitecore/templates/Feature/sugcon-2024/ITBusiness Component/ITBusiness/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{34FD3B66-B159-4A90-AE96-A623A13004EA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240530T082355Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jprajapati@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jprajapati@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a23ecba1-7db0-4cf1-a019-8031c41f5ab8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jprajapati@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240530T082403Z
